'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Lang = 'fr' | 'en' | 'ar'

const t18n: Record<Lang, Record<string, string>> = {
  /* ─────────────────────────── FRANÇAIS ─────────────────────────── */
  fr: {
    // ── Navbar
    'nav.home': 'Accueil',
    'nav.about': 'À propos de nous',
    'nav.services': 'Services',
    'nav.realisations': 'Réalisations',
    'nav.international': "À l'international",
    'nav.contact': 'Contact',
    'nav.cta': 'Demander un devis',

    // ── Hero
    'hero.eyebrow': 'GPE ENERGIES & SERVICES',
    'hero.title.part1': "L'énergie qui",
    'hero.title.highlight': 'donne vie',
    'hero.title.part2': 'à vos propriétés.',
    'hero.subtitle': "Énergies renouvelables, solutions solaires et bornes de recharge : votre avenir, notre expertise.",
    'hero.cta.contact': 'Contactez-nous',
    'hero.cta.services': 'Nos Services',
    'hero.stat.years': "Années d'expérience",
    'hero.stat.projects': 'Projets réalisés',
    'hero.stat.expertise': 'Expertises métier',
    'hero.stat.satisfaction': 'Clients satisfaits',

    // ── Services section
    'services.label': 'Nos expertises',
    'services.title': 'Des solutions complètes,\nde la conception à la réalisation.',
    'services.subtitle': "8 métiers complémentaires pour répondre à l'ensemble de vos besoins en énergie et en bâtiment.",
    'services.learnMore': 'En savoir plus',

    // ── References section
    'references.label': 'Nos réalisations',
    'references.title': 'Ils nous font confiance.',
    'references.subtitle': "Plus de 500 projets réalisés pour des maîtres d'ouvrage publics et privés partout en France.",
    'references.viewAll': 'Voir tous les projets',
    'references.featured': 'Projets de référence',
    'references.cta': 'Explorer tous nos projets',
    'references.category.pv': 'Photovoltaïque',
    'references.category.irve': 'IRVE',
    'references.category.electricite': 'Électricité',

    // ── About section
    'about.label': 'Notre histoire',
    'about.title.main': 'Bâtir un avenir électrique,',
    'about.title.highlight': 'ensemble.',
    'about.p1': "GPE – ENERGIES & SERVICES est une entreprise spécialisée dans un large éventail de domaines, offrant des solutions d’avenir pour un approvisionnement énergétique durable.",
    'about.p2': "Dans le secteur tertiaire et industriel, nous accompagnons nos clients avec des solutions techniques et économiques pour maximiser leur efficacité et réduire leurs coûts. Grâce à notre expertise dans les énergies renouvelables, telles que les systèmes solaires et les bornes de recharge pour véhicules électriques, nous proposons des solutions sur mesure pour aider les entreprises et les particuliers à passer à des sources d’énergie respectueuses de l’environnement.",
    'about.value0.title': 'Excellence technique',
    'about.value0.desc': "Chaque installation est réalisée dans les règles de l'art, certifiée et contrôlée par nos équipes qualifiées.",
    'about.value1.title': 'Engagement durable',
    'about.value1.desc': "Nous plaçons la transition énergétique au cœur de nos projets, pour un impact positif sur l'environnement.",
    'about.value2.title': 'Partenariat long terme',
    'about.value2.desc': 'Nos clients sont nos partenaires. Nous construisons des relations de confiance sur la durée, du projet à la maintenance.',
    'about.stat.founded': 'Création',
    'about.stat.team': 'Collaborateurs',
    'about.stat.region': "Région d'intervention",
    'about.stat.regionVal': 'Internationale',

    // ── Footer
    'footer.tagline': "Expert en installations électriques, énergies renouvelables et solutions CVC.",
    'footer.nav.title': 'Navigation',
    'footer.services.title': 'Nos services',
    'footer.contact.title': 'Contact',
    'footer.response': 'Réponse sous 24h ouvrées',
    'footer.copyright': 'Tous droits réservés.',
    'footer.links.legal': 'Mentions légales',
    'footer.links.privacy': 'Politique de confidentialité',
    'footer.links.cgv': 'CGV',
    'footer.nav.home': 'Accueil',
    'footer.nav.services': 'Services',
    'footer.nav.references': 'Réalisations',
    'footer.nav.about': 'À propos de nous',
    'footer.nav.contact': 'Contact',

    // ── Service page
    'service.back': 'Tous nos services',
    'service.expertise.label': 'Notre expertise',
    'service.expertise.title': 'Ce que nous réalisons pour vous',
    'service.benefits.title': 'Nos prestations incluses',
    'service.process.title': 'Notre processus',
    'service.process.0.title': 'Analyse & Étude',
    'service.process.0.desc': 'Audit technique de votre site et analyse de vos besoins spécifiques.',
    'service.process.1.title': 'Conception & Devis',
    'service.process.1.desc': 'Proposition technique détaillée avec chiffrage transparent et délais engagés.',
    'service.process.2.title': 'Réalisation',
    'service.process.2.desc': 'Exécution par nos équipes certifiées, avec suivi de chantier rigoureux.',
    'service.process.3.title': 'Réception & SAV',
    'service.process.3.desc': 'Mise en service, formation et contrat de maintenance adapté.',
    'service.cta.prefix': 'Un projet',
    'service.cta.suffix': '?',
    'service.cta.subtitle': 'Obtenez une étude personnalisée et un devis gratuit sous 24h.',
    'service.cta.quote': 'Demander un devis',
    'service.cta.call': 'Nous appeler',
    'service.certs.title': 'Certifications',
    'service.related.title': 'Services complémentaires',
    'service.projects.title': 'Projets réalisés',
    'service.projects.viewAll': 'Voir tous',

    // ── Service: Courants forts & faibles
    'service.courants-forts-faibles.title': 'Courants forts & faibles',
    'service.courants-forts-faibles.shortDesc': 'Installations électriques tertiaires et industrielles en courant fort et courant faible — du raccordement réseau à la mise en service complète.',
    'service.courants-forts-faibles.desc1': 'GPE Énergies & Services prend en charge l\'intégralité de vos installations électriques, de la conception des schémas unifilaires jusqu\'à la mise en service des équipements. Nos techniciens qualifiés interviennent sur tous types de bâtiments : tertiaires, industriels, commerciaux et résidentiels.',
    'service.courants-forts-faibles.desc2': 'Nous mettons notre expertise HTA/BT au service de vos projets en garantissant la conformité aux normes NF C 15-100 et la sécurité de vos installations. De la réalisation de tableaux électriques sur mesure à la maintenance préventive, nous vous accompagnons à chaque étape.',
    'service.courants-forts-faibles.benefit1': 'Conformité normes NF C 15-100',
    'service.courants-forts-faibles.benefit2': 'Expertise HTA/BT',
    'service.courants-forts-faibles.benefit3': 'Tableaux électriques sur mesure',
    'service.courants-forts-faibles.benefit4': 'Maintenance & diagnostic',

    // ── Service: Énergies renouvelables
    'service.energies-renouvelables.title': 'Énergies renouvelables',
    'service.energies-renouvelables.shortDesc': 'Solutions photovoltaïques clé en main, de l\'étude au génie civil — toiture, ombrières et centrales au sol pour particuliers, entreprises et collectivités.',
    'service.energies-renouvelables.desc1': 'Accélérez votre transition énergétique avec nos solutions photovoltaïques sur mesure. Notre équipe certifiée RGE conçoit, installe et met en service des systèmes solaires adaptés à vos besoins : autoconsommation totale ou partielle, vente de surplus ou systèmes hybrides avec stockage batterie.',
    'service.energies-renouvelables.desc2': 'Que vous soyez un particulier, une entreprise ou une collectivité, nous maximisons votre rentabilité et votre autonomie énergétique grâce à une étude personnalisée intégrant l\'ensemble des aides financières disponibles (MaPrimeRénov\', CEE, subventions locales).',
    'service.energies-renouvelables.benefit1': 'Panneaux photovoltaïques monocristallins',
    'service.energies-renouvelables.benefit2': 'Autoconsommation optimisée',
    'service.energies-renouvelables.benefit3': 'Stockage sur batterie',
    'service.energies-renouvelables.benefit4': 'Certification RGE QualiPV',

    // ── Service: Mobilité électrique
    'service.mobilite-electrique.title': 'Mobilité électrique',
    'service.mobilite-electrique.shortDesc': 'Conception et déploiement d\'infrastructures de recharge pour véhicules électriques — du raccordement réseau à l\'installation de bornes AC et DC.',
    'service.mobilite-electrique.desc1': 'Nous concevons et déployons des infrastructures de recharge pour véhicules électriques adaptées à tous les contextes : résidentiel individuel, copropriété, parc d\'entreprise, espace public ou commerce. Nos techniciens certifiés IRVE garantissent conformité et performance de chaque installation.',
    'service.mobilite-electrique.desc2': 'Nos solutions évolutives et connectées s\'appuient sur des équipements de pointe et des plateformes de supervision intelligente, vous permettant de gérer votre parc de bornes à distance, d\'optimiser la facturation et d\'anticiper les besoins en maintenance.',
    'service.mobilite-electrique.benefit1': 'Bornes résidentielles & professionnelles',
    'service.mobilite-electrique.benefit2': 'IRVE collectif & tertiaire',
    'service.mobilite-electrique.benefit3': 'Recharge rapide DC',
    'service.mobilite-electrique.benefit4': 'Supervision & télégestion',

    // ── Service: Rénovation énergétique
    'service.renovation-energetique.title': 'Rénovation énergétique',
    'service.renovation-energetique.shortDesc': 'Audit, conseil et travaux d\'amélioration pour réduire vos consommations et valoriser vos bâtiments.',
    'service.renovation-energetique.desc1': 'Notre bureau d\'experts réalise des audits énergétiques complets de vos bâtiments et vous propose un plan d\'actions priorisé pour améliorer votre performance énergétique. Nous intervenons sur toutes les composantes de l\'enveloppe du bâtiment : isolation thermique, menuiseries, ventilation et gestion technique.',
    'service.renovation-energetique.desc2': 'Certifiés RGE, nous vous accompagnons dans l\'accès aux aides financières (MaPrimeRénov\', Éco-PTZ, CEE) et pilotons les travaux jusqu\'à l\'obtention du label, pour une valorisation concrète de votre patrimoine immobilier.',
    'service.renovation-energetique.benefit1': 'Audit énergétique certifié',
    'service.renovation-energetique.benefit2': 'Isolation thermique & phonique',
    'service.renovation-energetique.benefit3': 'Accès aux aides financières',
    'service.renovation-energetique.benefit4': 'Optimisation DPE / label RE2020',

    // ── Service: Chauffage & climatisation
    'service.chauffage-climatisation.title': 'Chauffage & climatisation',
    'service.chauffage-climatisation.shortDesc': 'Solutions CVC sur mesure pour un confort thermique optimal — climatisation, chauffage, ventilation et pompes à chaleur, de l\'installation à la maintenance.',
    'service.chauffage-climatisation.desc1': 'GPE Énergies & Services conçoit et installe des systèmes CVC adaptés à chaque usage : pompes à chaleur air/air et air/eau, climatisation réversible multi-split, planchers chauffants et systèmes de ventilation double-flux. Nos équipes qualifiées interviennent en neuf comme en rénovation.',
    'service.chauffage-climatisation.desc2': 'Au-delà de l\'installation, nous assurons la maintenance préventive et corrective de vos équipements pour garantir performances, longévité et économies d\'énergie sur le long terme. Un service de télémaintenance est disponible pour les parcs multi-sites.',
    'service.chauffage-climatisation.benefit1': 'Pompes à chaleur (air/air, air/eau)',
    'service.chauffage-climatisation.benefit2': 'Climatisation réversible multi-split',
    'service.chauffage-climatisation.benefit3': 'Plancher chauffant hydraulique',
    'service.chauffage-climatisation.benefit4': 'Ventilation double-flux',

    // ── Service: Bureau d'études
    'service.bureau-etudes.title': "Bureau d'études",
    'service.bureau-etudes.shortDesc': 'Ingénierie et conception spécialisées en électricité et énergies renouvelables — études techniques, dimensionnement et suivi de projets.',
    'service.bureau-etudes.desc1': 'Notre bureau d\'études pluridisciplinaire accompagne maîtres d\'ouvrage et promoteurs depuis la phase de programmation jusqu\'à la réception des ouvrages. Nous réalisons études de conception (schémas, plans, CCTP), chiffrages détaillés et dossiers de consultation des entreprises (DCE).',
    'service.bureau-etudes.desc2': 'Grâce à nos outils de modélisation BIM et de simulation thermique dynamique, nous optimisons la conception de vos projets avant leur réalisation, réduisant les risques et maîtrisant les coûts de construction et d\'exploitation.',
    'service.bureau-etudes.benefit1': 'Études techniques & réglementaires',
    'service.bureau-etudes.benefit2': 'Modélisation BIM / maquette numérique',
    'service.bureau-etudes.benefit3': 'Suivi de chantier & OPC',
    'service.bureau-etudes.benefit4': "Maîtrise d'œuvre complète",

    // ── Service: GTB / KNX
    'service.smart-building.title': 'Smart Building',
    'service.smart-building.shortDesc': "Solutions de gestion technique du bâtiment basées sur le protocole KNX — automatisation, supervision et optimisation énergétique de vos installations.",
    'service.smart-building.desc1': "GPE Énergies & Services conçoit et déploie des systèmes de Gestion Technique du Bâtiment (GTB) basés sur le protocole KNX, standard international ouvert pour l'automatisation des bâtiments. Nos ingénieurs certifiés prennent en charge l'intégralité du projet, de l'étude de conception jusqu'à la mise en service et la formation des équipes d'exploitation.",
    'service.smart-building.desc2': "Grâce à la GTB et au protocole KNX, vous centralisez le pilotage de l'éclairage, des stores, du chauffage, de la climatisation et des contrôles d'accès sur une interface unique et intuitive. Cette approche permet de réduire significativement les consommations énergétiques tout en améliorant le confort des occupants.",
    'service.smart-building.benefit1': 'Programmation KNX certifiée ETS',
    'service.smart-building.benefit2': 'Supervision centralisée (BMS / SCADA)',
    'service.smart-building.benefit3': 'Intégration multi-protocoles (BACnet, Modbus)',
    'service.smart-building.benefit4': 'Télémaintenance et formation exploitation',

    // ── Service: VRD
    'service.vrd.title': 'VRD',
    'service.vrd.shortDesc': "Voiries, réseaux et divers — conception et réalisation de tous les aménagements extérieurs, réseaux secs et réseaux humides.",
    'service.vrd.desc1': "GPE Énergies & Services intervient sur l'ensemble des travaux de Voiries et Réseaux Divers (VRD) : terrassement, création et réhabilitation de voiries, réseaux d'assainissement, adduction d'eau potable, réseaux électriques extérieurs et éclairage public. Nos équipes coordonnent les interventions avec l'ensemble des concessionnaires pour assurer la conformité et la sécurité des ouvrages.",
    'service.vrd.desc2': "De l'aménagement de lotissements à la viabilisation de zones d'activité ou de parcs industriels, nous accompagnons maîtres d'ouvrage et collectivités de la phase études jusqu'à la réception des travaux. Notre approche globale garantit la cohérence technique entre les différents corps d'état et le respect des délais contractuels.",
    'service.vrd.benefit1': 'Terrassement et travaux de déblai / remblai',
    'service.vrd.benefit2': "Réseaux d'assainissement et d'adduction d'eau",
    'service.vrd.benefit3': 'Éclairage public et réseaux extérieurs',
    'service.vrd.benefit4': 'Suivi de chantier et coordination concessionnaires',


    // ── Contact page
    'contact.label': 'Contact',
    'contact.title': 'Parlons de votre projet.',
    'contact.sub': "Notre équipe répond sous 24h ouvrées. Que ce soit pour un devis, une étude de faisabilité ou une question technique, nous sommes à votre écoute.",
    'contact.info.phone': 'Téléphone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Adresse',
    'contact.hours.title': 'Horaires',
    'contact.hours.weekdays': 'Dimanche – Jeudi',
    'contact.hours.weekdaysTime': '8h00 – 18h00',
    'contact.hours.weekend': 'Vendredi – Samedi',
    'contact.hours.closed': 'Fermé',
    'contact.form.name': 'Nom complet *',
    'contact.form.namePlaceholder': 'Jean Dupont',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'jean@exemple.fr',
    'contact.form.phone': 'Téléphone',
    'contact.form.phonePlaceholder': '+213 XX XX XX XX',
    'contact.form.company': 'Société',
    'contact.form.companyPlaceholder': 'Votre entreprise',
    'contact.form.service': 'Service concerné',
    'contact.form.serviceDefault': 'Sélectionnez un service',
    'contact.form.message': 'Votre message *',
    'contact.form.messagePlaceholder': 'Décrivez votre projet ou votre demande...',
    'contact.form.messageError': 'Veuillez détailler votre message (min. 20 caractères)',
    'contact.form.submit': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.error': "Une erreur s'est produite. Veuillez réessayer ou nous contacter par téléphone.",
    'contact.form.privacy': "En envoyant ce formulaire, vous acceptez notre politique de confidentialité.",
    'contact.success.title': 'Message envoyé !',
    'contact.success.message': 'Merci pour votre message. Notre équipe vous répondra dans les 24h ouvrées.',
    'contact.success.button': 'Nouveau message',

    // ── Réalisations
    'realisations.label': 'Nos réalisations',
    'realisations.title': "Des projets qui parlent d'eux-mêmes.",
    'realisations.sub': "Plus de 500 projets réalisés pour des maîtres d'ouvrage publics et privés partout en France.",
    'realisations.all': 'Tous les projets',
    'realisations.empty': 'Aucun projet dans cette catégorie.',
    'realisations.cta.title': 'Un projet similaire ?',
    'realisations.cta.subtitle': "Discutons de votre projet. Notre équipe d'experts vous répond sous 24h ouvrées.",
    'realisations.cta.button': 'Nous contacter',

    // ── International
    'international.hero.label': 'Présence mondiale',
    'international.hero.title': 'Au-delà des frontières.',
    'international.hero.sub': "GPE Énergies & Services accompagne des projets d'envergure en Algérie et à l'international, en apportant son expertise technique sur chaque continent.",
    'international.locations.title': 'Nos implantations',
    'international.map.title': 'Une présence sur 3 continents.',
    'international.partners.title': 'Partenaires internationaux',
    'international.partners.subtitle': 'Des alliances stratégiques.',
    'international.certs.title': 'Certifications & qualifications',
    'international.certs.subtitle': 'Certifiés. Reconnus. Fiables.',
    'international.stat.0': 'Continents',
    'international.stat.1': 'Pays couverts',
    'international.stat.2': 'Projets internationaux',
    'international.stat.3': 'Partenaires mondiaux',
  },

  /* ─────────────────────────── ENGLISH ─────────────────────────── */
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.realisations': 'Projects',
    'nav.international': 'International',
    'nav.contact': 'Contact',
    'nav.cta': 'Request a quote',

    'hero.eyebrow': 'GPE ENERGIES & SERVICES',
    'hero.title.part1': 'The energy that',
    'hero.title.highlight': 'brings life',
    'hero.title.part2': 'to your properties.',
    'hero.subtitle': "Electrical installations, renewable energy, HVAC, civil works, and engineering consultancy. Integrated solutions for demanding professionals and local authorities.",
    'hero.cta.contact': 'Contact us',
    'hero.cta.services': 'Our Services',
    'hero.stat.years': 'Years of experience',
    'hero.stat.projects': 'Completed projects',
    'hero.stat.expertise': 'Areas of expertise',
    'hero.stat.satisfaction': 'Client satisfaction',

    'services.label': 'Our expertise',
    'services.title': 'Complete solutions,\nfrom design to delivery.',
    'services.subtitle': 'Eight complementary trades to meet all your energy and building needs.',
    'services.learnMore': 'Learn more',

    'references.label': 'Our projects',
    'references.title': 'They trust us.',
    'references.subtitle': 'Over 500 projects completed for public and private clients across France.',
    'references.viewAll': 'View all projects',
    'references.featured': 'Featured projects',
    'references.cta': 'Explore all our projects',
    'references.category.pv': 'Photovoltaic',
    'references.category.irve': 'EV Charging — IRVE',
    'references.category.electricite': 'Electrical Engineering & HVAC',

    'about.label': 'Our story',
    'about.title.main': 'Building an electrical future,',
    'about.title.highlight': 'together.',
    'about.p1': 'Founded in 2008 in Lyon, GPE Énergies & Services was built on the conviction that technical excellence and energy innovation must go hand in hand. Over fifteen years, we have supported hundreds of project owners in their transition toward more efficient, economical, and sustainable buildings.',
    'about.p2': 'Our multidisciplinary approach — electricity, renewables, HVAC, civil works, and engineering — allows us to handle a project in its entirety, ensuring technical coherence, deadline compliance, and cost control.',
    'about.value0.title': 'Technical Excellence',
    'about.value0.desc': 'Every installation is carried out to the highest standards, certified and inspected by our qualified teams.',
    'about.value1.title': 'Sustainable Commitment',
    'about.value1.desc': 'We place the energy transition at the heart of our projects, for a positive environmental impact.',
    'about.value2.title': 'Long-term Partnership',
    'about.value2.desc': 'Our clients are our partners. We build lasting trust-based relationships, from project inception through maintenance.',
    'about.stat.founded': 'Founded',
    'about.stat.team': 'Team members',
    'about.stat.region': 'Service region',
    'about.stat.regionVal': 'South',

    'footer.tagline': 'Expert in electrical installations, renewable energy, and HVAC solutions since 2008.',
    'footer.nav.title': 'Navigation',
    'footer.services.title': 'Our services',
    'footer.contact.title': 'Contact',
    'footer.response': 'Response within 24 business hours',
    'footer.copyright': 'All rights reserved.',
    'footer.links.legal': 'Legal notices',
    'footer.links.privacy': 'Privacy policy',
    'footer.links.cgv': 'Terms of service',
    'footer.nav.home': 'Home',
    'footer.nav.services': 'Services',
    'footer.nav.references': 'Projects',
    'footer.nav.about': 'About us',
    'footer.nav.contact': 'Contact',

    'service.back': 'All our services',
    'service.expertise.label': 'Our expertise',
    'service.expertise.title': 'What we deliver for you',
    'service.benefits.title': 'Included services',
    'service.process.title': 'Our process',
    'service.process.0.title': 'Analysis & Study',
    'service.process.0.desc': 'Technical audit of your site and analysis of your specific needs.',
    'service.process.1.title': 'Design & Quote',
    'service.process.1.desc': 'Detailed technical proposal with transparent pricing and committed timelines.',
    'service.process.2.title': 'Implementation',
    'service.process.2.desc': 'Execution by our certified teams with rigorous site supervision.',
    'service.process.3.title': 'Handover & Support',
    'service.process.3.desc': 'Commissioning, training, and a tailored maintenance contract.',
    'service.cta.prefix': 'A',
    'service.cta.suffix': 'project?',
    'service.cta.subtitle': 'Get a personalised study and a free quote within 24 hours.',
    'service.cta.quote': 'Request a quote',
    'service.cta.call': 'Call us',
    'service.certs.title': 'Certifications',
    'service.related.title': 'Complementary services',
    'service.projects.title': 'Completed projects',
    'service.projects.viewAll': 'View all',

    
    // ── Service: High & Low Voltage Systems
    'service.courants-forts-faibles.title': 'High & Low Voltage Systems',
    'service.courants-forts-faibles.shortDesc': 'Design and installation of LV/HV electrical systems, from main distribution boards to terminal equipment.',
    'service.courants-forts-faibles.desc1': 'GPE Énergies & Services handles the full scope of your electrical infrastructure — from single-line diagram design through to equipment commissioning. Our certified engineers and technicians serve all building types: commercial, industrial, retail, and residential.',
    'service.courants-forts-faibles.desc2': 'Drawing on deep LV/HV expertise, we ensure full compliance with applicable wiring regulations and deliver custom-built switchboards, preventive maintenance programmes, and diagnostic services to keep your installations performing at their best.',
    'service.courants-forts-faibles.benefit1': 'LV/HV Wiring Regulations Compliance',
    'service.courants-forts-faibles.benefit2': 'HV/LV Switchgear & Distribution',
    'service.courants-forts-faibles.benefit3': 'Custom Electrical Panels & Boards',
    'service.courants-forts-faibles.benefit4': 'Maintenance & Fault Diagnostics',

    // ── Service: Renewable Energy
    'service.energies-renouvelables.title': 'Renewable Energy',
    'service.energies-renouvelables.shortDesc': 'Tailored solar PV and battery storage solutions to accelerate your energy transition.',
    'service.energies-renouvelables.desc1': 'Our RGE-certified team designs, installs, and commissions solar PV systems matched to your consumption profile — self-consumption, surplus feed-in, or hybrid battery storage. We serve homeowners, businesses, and public-sector clients with equal attention to detail.',
    'service.energies-renouvelables.desc2': 'Every project includes a full financial study covering available incentives so you can make informed decisions and maximise your return on investment from day one.',
    'service.energies-renouvelables.benefit1': 'Monocrystalline Solar Panels',
    'service.energies-renouvelables.benefit2': 'Self-Consumption Optimisation',
    'service.energies-renouvelables.benefit3': 'Battery Energy Storage',
    'service.energies-renouvelables.benefit4': 'RGE QualiPV Certified Installer',

    // ── Service: Electric Vehicle Charging
    'service.mobilite-electrique.title': 'Electric Vehicle Charging',
    'service.mobilite-electrique.shortDesc': 'End-to-end EV charging infrastructure, from residential wallboxes to smart networked charging hubs.',
    'service.mobilite-electrique.desc1': 'We design and deploy EV charging infrastructure for all settings: private homes, residential complexes, corporate fleets, public car parks, and retail sites. All installations are carried out by our IRVE-certified technicians, ensuring safety, regulatory compliance, and optimal performance.',
    'service.mobilite-electrique.desc2': 'Our scalable, connected solutions integrate with smart energy management platforms, enabling remote fleet monitoring, dynamic load balancing, and automated billing — future-proofing your charging infrastructure as EV adoption grows.',
    'service.mobilite-electrique.benefit1': 'Home & Commercial Chargers',
    'service.mobilite-electrique.benefit2': 'Multi-Unit Residential (IRVE)',
    'service.mobilite-electrique.benefit3': 'DC Fast Charging',
    'service.mobilite-electrique.benefit4': 'Remote Monitoring & Fleet Management',

    // ── Service: Energy Renovation
    'service.renovation-energetique.title': 'Energy Renovation',
    'service.renovation-energetique.shortDesc': 'Energy auditing, consultancy, and renovation works to cut consumption and enhance building value.',
    'service.renovation-energetique.desc1': 'Our energy experts carry out comprehensive building audits and deliver a prioritised action plan to improve your energy performance rating. We address every element of the building envelope: thermal insulation, glazing upgrades, HVAC improvements, and smart building controls.',
    'service.renovation-energetique.desc2': 'As an RGE-certified firm, we guide you through every available funding scheme and supervise all works through to final label certification — delivering measurable, lasting value for your property portfolio.',
    'service.renovation-energetique.benefit1': 'Certified Energy Auditing',
    'service.renovation-energetique.benefit2': 'Thermal & Acoustic Insulation',
    'service.renovation-energetique.benefit3': 'Access to Government Incentives',
    'service.renovation-energetique.benefit4': 'EPC Optimisation & RE2020 Compliance',

    // ── Service: Heating & Air Conditioning
    'service.chauffage-climatisation.title': 'Heating & Air Conditioning',
    'service.chauffage-climatisation.shortDesc': 'End-to-end HVAC solutions for optimal thermal comfort, from installation through to long-term maintenance.',
    'service.chauffage-climatisation.desc1': 'GPE Énergies & Services designs and installs HVAC systems tailored to every application: air-to-air and air-to-water heat pumps, reversible multi-split systems, underfloor heating, and heat-recovery ventilation. Our Qualibat-certified teams work on new builds and refurbishments alike.',
    'service.chauffage-climatisation.desc2': 'Beyond installation, we provide preventive and corrective maintenance to keep your equipment running at peak efficiency — extending service life and reducing energy costs. Remote monitoring packages are available for multi-site clients.',
    'service.chauffage-climatisation.benefit1': 'Air-to-Air & Air-to-Water Heat Pumps',
    'service.chauffage-climatisation.benefit2': 'Reversible Multi-Split AC',
    'service.chauffage-climatisation.benefit3': 'Hydronic Underfloor Heating',
    'service.chauffage-climatisation.benefit4': 'Heat-Recovery Ventilation (HRV)',

    // ── Service: Engineering Office
    'service.bureau-etudes.title': 'Engineering Office',
    'service.bureau-etudes.shortDesc': 'Multidisciplinary engineering, project design, and contract administration for electrical and energy projects.',
    'service.bureau-etudes.desc1': 'Our in-house engineering team supports project owners and developers from early-stage feasibility right through to project handover. We produce full design packages — single-line diagrams, layout drawings, technical specifications, and tender documents — across all disciplines.',
    'service.bureau-etudes.desc2': 'With BIM modelling and dynamic thermal simulation, we optimise every design before construction begins, minimising risk, controlling life-cycle costs, and ensuring regulatory compliance from day one.',
    'service.bureau-etudes.benefit1': 'Technical & Regulatory Studies',
    'service.bureau-etudes.benefit2': 'BIM / Digital Building Models',
    'service.bureau-etudes.benefit3': 'Site Supervision & Project Programming',
    'service.bureau-etudes.benefit4': 'Full Contract Administration (MOE)',

    // ── Service: BMS / KNX Systems
    'service.smart-building.title': 'BMS / KNX Systems',
    'service.smart-building.shortDesc': 'Design and deployment of Building Management Systems based on the KNX protocol for intelligent automation and energy optimisation of your premises.',
    'service.smart-building.desc1': 'GPE Énergies & Services designs and deploys Building Management Systems (BMS) built on the KNX protocol — the open international standard for building automation. Our certified engineers manage the full project lifecycle, from conceptual design through to commissioning and operator training.',
    'service.smart-building.desc2': 'By integrating BMS and KNX, you centralise control of lighting, blinds, heating, air conditioning, and access systems on a single intuitive interface. This approach enables significant energy savings while improving occupant comfort and operational efficiency across all building types.',
    'service.smart-building.benefit1': 'KNX ETS-Certified Programming',
    'service.smart-building.benefit2': 'Centralised Supervision (BMS / SCADA)',
    'service.smart-building.benefit3': 'Multi-Protocol Integration (BACnet, Modbus)',
    'service.smart-building.benefit4': 'Remote Monitoring & Operator Training',

    // ── Service: Civil Engineering & Site Works
    'service.vrd.title': 'Civil Engineering & Site Works',
    'service.vrd.shortDesc': 'Roads, utilities, and external networks: design and construction of all site infrastructure, drainage, earthworks, and external service connections.',
    'service.vrd.desc1': 'GPE Énergies & Services handles the full scope of civil engineering and utility works: earthworks, road construction and rehabilitation, drainage networks, water supply, external electrical networks, street lighting, and telecoms infrastructure. Our teams coordinate with all utility concessionaires to ensure regulatory compliance and structural safety throughout.',
    'service.vrd.desc2': 'From residential developments and business parks to industrial zones and public spaces, we support project owners and local authorities from the initial design phase through to project handover. Our integrated approach ensures technical coherence across all trades and adherence to contractual deadlines.',
    'service.vrd.benefit1': 'Earthworks & Site Preparation',
    'service.vrd.benefit2': 'Drainage, Sewerage & Water Supply Networks',
    'service.vrd.benefit3': 'Street Lighting & External Electrical Networks',
    'service.vrd.benefit4': 'Site Management & Utility Coordination',


    'contact.label': 'Contact',
    'contact.title': "Let's talk about your project.",
    'contact.sub': 'Our team responds within 24 business hours. Whether for a quote, a feasibility study, or a technical question, we are here for you.',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Address',
    'contact.hours.title': 'Opening hours',
    'contact.hours.weekdays': 'Monday – Friday',
    'contact.hours.weekdaysTime': '8:00 AM – 6:00 PM',
    'contact.hours.weekend': 'Saturday – Sunday',
    'contact.hours.closed': 'Closed',
    'contact.form.name': 'Full name *',
    'contact.form.namePlaceholder': 'John Smith',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'john@example.com',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+33 6 XX XX XX XX',
    'contact.form.company': 'Company',
    'contact.form.companyPlaceholder': 'Your company',
    'contact.form.service': 'Service needed',
    'contact.form.serviceDefault': 'Select a service',
    'contact.form.message': 'Your message *',
    'contact.form.messagePlaceholder': 'Describe your project or request...',
    'contact.form.messageError': 'Please provide more details (min. 20 characters)',
    'contact.form.submit': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.error': 'Something went wrong. Please try again or contact us by phone.',
    'contact.form.privacy': 'By submitting this form, you agree to our privacy policy.',
    'contact.success.title': 'Message sent!',
    'contact.success.message': 'Thank you for your message. Our team will get back to you within 24 business hours.',
    'contact.success.button': 'New message',

    'realisations.label': 'Our projects',
    'realisations.title': 'Projects that speak for themselves.',
    'realisations.sub': 'Over 500 projects completed for public and private clients across France.',
    'realisations.all': 'All projects',
    'realisations.empty': 'No projects in this category.',
    'realisations.cta.title': 'A similar project?',
    'realisations.cta.subtitle': 'Let\'s discuss your project. Our expert team responds within 24 business hours.',
    'realisations.cta.button': 'Contact us',

    'international.hero.label': 'Global presence',
    'international.hero.title': 'Beyond borders.',
    'international.hero.sub': 'GPE Énergies & Services supports large-scale projects in France and internationally, bringing technical expertise to every continent.',
    'international.locations.title': 'Our locations',
    'international.map.title': 'Present across 3 continents.',
    'international.partners.title': 'International partners',
    'international.partners.subtitle': 'Strategic alliances.',
    'international.certs.title': 'Certifications & qualifications',
    'international.certs.subtitle': 'Certified. Recognised. Reliable.',
    'international.stat.0': 'Continents',
    'international.stat.1': 'Countries served',
    'international.stat.2': 'International projects',
    'international.stat.3': 'Global partners',
  },

  /* ─────────────────────────── ARABIC ─────────────────────────── */
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.realisations': 'مشاريعنا',
    'nav.international': 'دولي',
    'nav.contact': 'اتصل بنا',
    'nav.cta': 'طلب عرض أسعار',

    'hero.eyebrow': 'الجزائر العاصمة',
    'hero.title.part1': 'الطاقة التي',
    'hero.title.highlight': 'تُحيي',
    'hero.title.part2': 'ممتلكاتكم.',
    'hero.subtitle': 'تركيبات كهربائية، طاقات متجددة، تكييف وتهوية، بنية تحتية، ومكتب الدراسات. حلول متكاملة للمحترفين والهيئات الحكومية المتطلبة.',
    'hero.cta.contact': 'تواصل معنا',
    'hero.cta.services': 'خدماتنا',
    'hero.stat.years': 'سنوات خبرة',
    'hero.stat.projects': 'مشروع منجز',
    'hero.stat.expertise': 'تخصص تقني',
    'hero.stat.satisfaction': 'رضا العملاء',

    'services.label': 'خبراتنا',
    'services.title': 'حلول شاملة\nمن التصميم إلى التنفيذ.',
    'services.subtitle': 'ثمانية تخصصات متكاملة لتلبية كافة احتياجاتكم في مجال الطاقة والبناء.',
    'services.learnMore': 'اكتشف المزيد',

    'references.label': 'إنجازاتنا',
    'references.title': 'يثقون بنا.',
    'references.subtitle': 'أكثر من ٥٠٠ مشروع منجز لعملاء من القطاع العام والخاص في جميع أنحاء فرنسا.',
    'references.viewAll': 'عرض جميع المشاريع',
    'references.featured': 'مشاريع مرجعية',
    'references.cta': 'استكشف جميع مشاريعنا',
    'references.category.pv': 'الطاقة الشمسية الكهروضوئية',
    'references.category.irve': 'شحن المركبات الكهربائية',
    'references.category.electricite': 'الكهرباء والتكييف',

    'about.label': 'قصتنا',
    'about.title.main': 'نبني مستقبلاً كهربائياً،',
    'about.title.highlight': 'معاً.',
    'about.p1': 'تأسست GPE Énergies & Services عام ٢٠٠٨ في ليون، إيماناً بأن التميّز التقني والابتكار في مجال الطاقة يجب أن يسيرا جنباً إلى جنب. وعلى مدى خمسة عشر عاماً، رافقنا المئات من أصحاب المشاريع في مسيرتهم نحو مبانٍ أكثر كفاءةً وترشيداً واستدامةً.',
    'about.p2': 'يُتيح لنا نهجنا متعدد التخصصات — من الكهرباء والطاقات المتجددة، إلى التكييف والبنية التحتية والهندسة — إدارة المشروع بأكمله بتناسق تقني، والتزام بالمواعيد، والتحكم الكامل في التكاليف.',
    'about.value0.title': 'التميز التقني',
    'about.value0.desc': 'كل تركيب يُنجز وفق أعلى المعايير المهنية، معتمداً ومفحوصاً من قِبل فرقنا المؤهلة.',
    'about.value1.title': 'الالتزام بالاستدامة',
    'about.value1.desc': 'نضع التحول الطاقوي في صميم مشاريعنا، سعياً لأثر إيجابي حقيقي على البيئة.',
    'about.value2.title': 'شراكة طويلة الأمد',
    'about.value2.desc': 'عملاؤنا هم شركاؤنا الحقيقيون. نبني علاقات ثقة راسخة، من الإنجاز إلى الصيانة.',
    'about.stat.founded': 'تأسيس',
    'about.stat.team': 'موظف',
    'about.stat.region': 'منطقة التدخل',
    'about.stat.regionVal': 'الجنوب',

    'footer.tagline': 'خبراء في التركيبات الكهربائية والطاقات المتجددة وأنظمة التكييف منذ ٢٠٠٨.',
    'footer.nav.title': 'التنقل',
    'footer.services.title': 'خدماتنا',
    'footer.contact.title': 'تواصل معنا',
    'footer.response': 'رد خلال ٢٤ ساعة عمل',
    'footer.copyright': 'جميع الحقوق محفوظة.',
    'footer.links.legal': 'الإشعارات القانونية',
    'footer.links.privacy': 'سياسة الخصوصية',
    'footer.links.cgv': 'الشروط العامة',
    'footer.nav.home': 'الرئيسية',
    'footer.nav.services': 'الخدمات',
    'footer.nav.references': 'مشاريعنا',
    'footer.nav.about': 'من نحن',
    'footer.nav.contact': 'اتصل بنا',

    'service.back': 'جميع خدماتنا',
    'service.expertise.label': 'خبرتنا',
    'service.expertise.title': 'ما نُنجزه من أجلكم',
    'service.benefits.title': 'الخدمات المشمولة',
    'service.process.title': 'منهجيتنا',
    'service.process.0.title': 'التحليل والدراسة',
    'service.process.0.desc': 'تدقيق تقني لموقعكم وتحليل شامل لاحتياجاتكم الخاصة.',
    'service.process.1.title': 'التصميم والعرض',
    'service.process.1.desc': 'مقترح تقني مفصّل بتسعير شفاف والتزام بالمواعيد.',
    'service.process.2.title': 'التنفيذ',
    'service.process.2.desc': 'تنفيذ احترافي بواسطة فرقنا المعتمدة وإشراف ميداني دقيق.',
    'service.process.3.title': 'الاستلام والدعم',
    'service.process.3.desc': 'التشغيل والتدريب وعقد الصيانة الأنسب لاحتياجاتكم.',
    'service.cta.prefix': 'مشروع',
    'service.cta.suffix': '؟',
    'service.cta.subtitle': 'احصل على دراسة مخصصة وعرض أسعار مجاني خلال ٢٤ ساعة.',
    'service.cta.quote': 'طلب عرض أسعار',
    'service.cta.call': 'اتصل بنا',
    'service.certs.title': 'الشهادات والاعتمادات',
    'service.related.title': 'خدمات مكملة',
    'service.projects.title': 'المشاريع المنجزة',
    'service.projects.viewAll': 'عرض الكل',

    // ── Service: التيارات القوية والضعيفة
    'service.courants-forts-faibles.title': 'التيارات القوية والضعيفة',
    'service.courants-forts-faibles.shortDesc': 'تصميم وتنفيذ منظومات التوزيع الكهربائي للجهد المنخفض والمتوسط، من اللوحة الرئيسية إلى المعدات الطرفية.',
    'service.courants-forts-faibles.desc1': 'تتولى GPE Énergies & Services تنفيذ كامل منظومتكم الكهربائية، من وضع المخططات الأحادية وحتى تشغيل المعدات. يتدخل تقنيونا المعتمدون في جميع أنواع المباني: المكتبية والصناعية والتجارية والسكنية، بضمان الجودة واحترام المعايير المعتمدة.',
    'service.courants-forts-faibles.desc2': 'نوظّف خبرتنا العميقة في أنظمة الجهد المتوسط والمنخفض لضمان مطابقة التركيبات للمعايير التقنية، وتنفيذ لوحات التوزيع المخصصة، وتقديم خدمات الصيانة الوقائية والتشخيص لضمان استمرارية الأداء.',
    'service.courants-forts-faibles.benefit1': 'مطابقة معايير التوصيلات الكهربائية',
    'service.courants-forts-faibles.benefit2': 'خبرة في الجهد المتوسط والمنخفض',
    'service.courants-forts-faibles.benefit3': 'لوحات توزيع كهربائية مخصصة',
    'service.courants-forts-faibles.benefit4': 'الصيانة والتشخيص الكهربائي',

    // ── Service: الطاقات المتجددة
    'service.energies-renouvelables.title': 'الطاقات المتجددة',
    'service.energies-renouvelables.shortDesc': 'تركيب أنظمة الطاقة الشمسية الكهروضوئية وحلول تخزين الطاقة لتسريع انتقالكم نحو الطاقة النظيفة.',
    'service.energies-renouvelables.desc1': 'يصمم فريقنا المعتمد ويركّب وينفّذ أنظمة الطاقة الشمسية وفق احتياجاتكم الفعلية: الاستهلاك الذاتي الكلي أو الجزئي، بيع الفائض، أو الأنظمة الهجينة مع تخزين البطاريات. نخدم الأفراد والمؤسسات والهيئات العامة بنفس المستوى من الكفاءة والدقة.',
    'service.energies-renouvelables.desc2': 'يشمل كل مشروع دراسة مالية شاملة تتضمن الدعم الحكومي المتاح، لتتخذوا قراراتكم على أسس موثوقة وتحققوا أقصى عائد على الاستثمار منذ اليوم الأول.',
    'service.energies-renouvelables.benefit1': 'ألواح شمسية كهروضوئية عالية الكفاءة',
    'service.energies-renouvelables.benefit2': 'تحسين الاستهلاك الذاتي للطاقة',
    'service.energies-renouvelables.benefit3': 'أنظمة تخزين الطاقة بالبطاريات',
    'service.energies-renouvelables.benefit4': 'اعتماد مؤسسة QualiPV / RGE',

    // ── Service: التنقل الكهربائي
    'service.mobilite-electrique.title': 'التنقل الكهربائي',
    'service.mobilite-electrique.shortDesc': 'تركيب وتشغيل بنية تحتية متكاملة لشحن المركبات الكهربائية، من محطة الشحن المنزلي إلى الشبكات الذكية.',
    'service.mobilite-electrique.desc1': 'نصمم وننشر منظومات شحن المركبات الكهربائية لجميع الاستخدامات: المنازل والعمارات السكنية، وأسطول المؤسسات، ومواقف السيارات العامة والمراكز التجارية. ينجز جميع الأعمال تقنيونا المعتمدون لضمان السلامة والأداء الأمثل.',
    'service.mobilite-electrique.desc2': 'تتكامل حلولنا القابلة للتوسع مع منصات الإدارة الذكية لتمكينكم من مراقبة الأسطول عن بُعد، وموازنة الأحمال ديناميكيًا، وإدارة الفوترة بشكل آلي.',
    'service.mobilite-electrique.benefit1': 'محطات شحن منزلية ومهنية',
    'service.mobilite-electrique.benefit2': 'تركيبات جماعية في العمارات (IRVE)',
    'service.mobilite-electrique.benefit3': 'شحن سريع بالتيار المستمر',
    'service.mobilite-electrique.benefit4': 'الإدارة عن بُعد ومراقبة الأسطول',

    // ── Service: تجديد الكفاءة الطاقوية
    'service.renovation-energetique.title': 'تجديد الكفاءة الطاقوية',
    'service.renovation-energetique.shortDesc': 'مراجعة وتحسين الأداء الطاقوي للمباني لخفض الاستهلاك ورفع قيمة العقار.',
    'service.renovation-energetique.desc1': 'يجري خبراؤنا مراجعات طاقوية شاملة للمباني ويضعون خطة إجراءات مرتبة حسب الأولوية لتحسين معدل الأداء الطاقوي. نتدخل على جميع مكونات غلاف المبنى: العزل الحراري، الفتحات والنوافذ، تحديث أنظمة التكييف، والتحكم التقني.',
    'service.renovation-energetique.desc2': 'بوصفنا شركة معتمدة RGE، نرشدكم إلى جميع الدعم المالي المتاح ونشرف على الأشغال حتى الحصول على الاعتماد النهائي، لتحقيق قيمة ملموسة ومستدامة لمحفظتكم العقارية.',
    'service.renovation-energetique.benefit1': 'مراجعة طاقوية معتمدة',
    'service.renovation-energetique.benefit2': 'عزل حراري وصوتي',
    'service.renovation-energetique.benefit3': 'الاستفادة من الدعم المالي الحكومي',
    'service.renovation-energetique.benefit4': 'تحسين تصنيف الأداء الطاقوي (DPE)',

    // ── Service: التدفئة والتكييف
    'service.chauffage-climatisation.title': 'التدفئة والتكييف',
    'service.chauffage-climatisation.shortDesc': 'حلول تكييف وتهوية متكاملة لضمان الراحة الحرارية المثلى، من التركيب إلى الصيانة الدائمة.',
    'service.chauffage-climatisation.desc1': 'تصمم GPE Énergies & Services وتركّب منظومات التدفئة والتهوية والتكييف المناسبة لكل استخدام: مضخات الحرارة هواء/هواء وهواء/ماء، أنظمة التكييف المقلوب المتعدد، التدفئة بالأرضية الإشعاعية، وأنظمة التهوية المزدوجة.',
    'service.chauffage-climatisation.desc2': 'نقدم خدمات الصيانة الوقائية والتصحيحية للحفاظ على كفاءة معداتكم وإطالة عمرها التشغيلي وتقليص فاتورة الطاقة. كما تتوفر خدمة المراقبة عن بُعد لعملاء المواقع المتعددة.',
    'service.chauffage-climatisation.benefit1': 'مضخات الحرارة (هواء/هواء وهواء/ماء)',
    'service.chauffage-climatisation.benefit2': 'تكييف مقلوب متعدد الوحدات',
    'service.chauffage-climatisation.benefit3': 'تدفئة بالأرضية الهيدروليكية',
    'service.chauffage-climatisation.benefit4': 'تهوية باسترداد الحرارة (HRV)',

    // ── Service: مكتب الدراسات
    'service.bureau-etudes.title': 'مكتب الدراسات',
    'service.bureau-etudes.shortDesc': 'هندسة وتصميم وإدارة عقود المشاريع الكهربائية والطاقوية.',
    'service.bureau-etudes.desc1': 'يرافق مكتب الدراسات الداخلي لدينا أصحاب المشاريع والمطورين من مرحلة الجدوى الأولية وحتى تسليم الأعمال. ننجز حزم التصميم الكاملة — المخططات الأحادية، المخططات المعمارية، المواصفات التقنية، ووثائق طلب العروض — عبر جميع التخصصات.',
    'service.bureau-etudes.desc2': 'بفضل نمذجة BIM والمحاكاة الحرارية الديناميكية، نُحسّن كل تصميم قبل بدء التنفيذ لتقليل المخاطر والتحكم في تكاليف دورة الحياة وضمان الامتثال للوائح منذ اليوم الأول.',
    'service.bureau-etudes.benefit1': 'دراسات تقنية وتنظيمية',
    'service.bureau-etudes.benefit2': 'نمذجة BIM والنموذج الرقمي للمبنى',
    'service.bureau-etudes.benefit3': 'الإشراف على المواقع وبرمجة المشاريع',
    'service.bureau-etudes.benefit4': 'إدارة عقود كاملة (MOE)',

    // ── Service: أنظمة GTB / KNX
    'service.smart-building.title': 'أنظمة GTB / KNX',
    'service.smart-building.shortDesc': 'تصميم ونشر أنظمة الإدارة التقنية للمباني وفق بروتوكول KNX لأتمتة مبانيكم وتحسين استهلاككم الطاقوي.',
    'service.smart-building.desc1': 'تصمم GPE Énergies & Services وتنشر أنظمة الإدارة التقنية للمباني (GTB) المبنية على بروتوكول KNX، المعيار الدولي المفتوح لأتمتة المباني. يتولى مهندسونا المعتمدون إدارة دورة حياة المشروع الكاملة، من التصميم المفاهيمي وحتى التشغيل وتدريب فرق الاستغلال.',
    'service.smart-building.desc2': 'بفضل تكامل GTB وKNX، تتمكنون من مركزة التحكم في الإضاءة والستائر والتدفئة والتكييف وأنظمة التحكم في الوصول على واجهة واحدة وسهلة الاستخدام. يُتيح هذا النهج توفيرات طاقوية ملموسة مع تحسين راحة شاغلي المبنى وكفاءة التشغيل.',
    'service.smart-building.benefit1': 'برمجة KNX معتمدة وفق معيار ETS',
    'service.smart-building.benefit2': 'إشراف مركزي (BMS / SCADA)',
    'service.smart-building.benefit3': 'تكامل متعدد البروتوكولات (BACnet، Modbus)',
    'service.smart-building.benefit4': 'صيانة عن بُعد وتدريب فرق التشغيل',

    // ── Service: الطرق والشبكات والتهيئة
    'service.vrd.title': 'الطرق والشبكات والتهيئة',
    'service.vrd.shortDesc': 'التصميم وإنجاز جميع الشبكات الخارجية وأعمال الصرف الصحي والترابية وتهيئة المواقع.',
    'service.vrd.desc1': 'تتولى GPE Énergies & Services تنفيذ كامل أعمال الطرق والشبكات والتهيئة (VRD): أعمال ترابية، إنشاء وتأهيل الطرق، شبكات الصرف الصحي، إمداد المياه الصالحة للشرب، الشبكات الكهربائية الخارجية والإنارة العامة. تنسق فرقنا التدخلات مع جميع أصحاب الامتيازات لضمان الامتثال التقني وسلامة المنشآت.',
    'service.vrd.desc2': 'سواء لمجزأة سكنية أو منطقة نشاط أو حديقة صناعية أو فضاءات عامة، نرافق أصحاب المشاريع والجماعات من مرحلة الدراسة حتى الاستلام النهائي. يضمن نهجنا الشامل التناسق التقني بين مختلف التخصصات والالتزام بالمواعيد التعاقدية.',
    'service.vrd.benefit1': 'أعمال الترابية والحفر والردم',
    'service.vrd.benefit2': 'شبكات الصرف الصحي وإمداد المياه',
    'service.vrd.benefit3': 'الإنارة العامة والشبكات الكهربائية الخارجية',
    'service.vrd.benefit4': 'الإشراف على المواقع وتنسيق أصحاب الامتيازات',

    'contact.label': 'تواصل معنا',
    'contact.title': 'لنتحدث عن مشروعكم.',
    'contact.sub': 'يرد فريقنا خلال ٢٤ ساعة عمل. سواء لعرض أسعار أو دراسة جدوى أو سؤال تقني، نحن هنا لمساعدتكم.',
    'contact.info.phone': 'هاتف',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.address': 'العنوان',
    'contact.hours.title': 'أوقات العمل',
    'contact.hours.weekdays': 'الإثنين – الجمعة',
    'contact.hours.weekdaysTime': '٨:٠٠ – ١٨:٠٠',
    'contact.hours.weekend': 'السبت – الأحد',
    'contact.hours.closed': 'مغلق',
    'contact.form.name': 'الاسم الكامل *',
    'contact.form.namePlaceholder': 'محمد الأمين',
    'contact.form.email': 'البريد الإلكتروني *',
    'contact.form.emailPlaceholder': 'example@domain.com',
    'contact.form.phone': 'الهاتف',
    'contact.form.phonePlaceholder': '+213 6 XX XX XX XX',
    'contact.form.company': 'الشركة',
    'contact.form.companyPlaceholder': 'اسم شركتكم',
    'contact.form.service': 'الخدمة المطلوبة',
    'contact.form.serviceDefault': 'اختر خدمة',
    'contact.form.message': 'رسالتكم *',
    'contact.form.messagePlaceholder': 'صفوا مشروعكم أو طلبكم...',
    'contact.form.messageError': 'يُرجى تفصيل رسالتكم (٢٠ حرفاً على الأقل)',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.sending': 'جارٍ الإرسال...',
    'contact.form.error': 'حدث خطأ. يرجى المحاولة مجدداً أو الاتصال بنا هاتفياً.',
    'contact.form.privacy': 'بإرسال هذا النموذج، تقبلون سياسة الخصوصية الخاصة بنا.',
    'contact.success.title': 'تم إرسال رسالتكم!',
    'contact.success.message': 'شكراً لتواصلكم. سيرد فريقنا خلال ٢٤ ساعة عمل.',
    'contact.success.button': 'رسالة جديدة',

    'realisations.label': 'إنجازاتنا',
    'realisations.title': 'مشاريع تتحدث عن نفسها.',
    'realisations.sub': 'أكثر من ٥٠٠ مشروع منجز لعملاء من القطاع العام والخاص في جميع أنحاء فرنسا.',
    'realisations.all': 'جميع المشاريع',
    'realisations.empty': 'لا توجد مشاريع في هذه الفئة.',
    'realisations.cta.title': 'مشروع مماثل؟',
    'realisations.cta.subtitle': 'لنتحدث عن مشروعكم. فريق خبرائنا يرد خلال ٢٤ ساعة عمل.',
    'realisations.cta.button': 'تواصل معنا',

    'international.hero.label': 'حضور عالمي',
    'international.hero.title': 'ما وراء الحدود.',
    'international.hero.sub': 'تدعم GPE Énergies & Services مشاريع واسعة النطاق في فرنسا وعلى الصعيد الدولي، مع تقديم خبرات تقنية راسخة على كل قارة.',
    'international.locations.title': 'مواقعنا',
    'international.map.title': 'حضور على ٣ قارات.',
    'international.partners.title': 'شركاؤنا الدوليون',
    'international.partners.subtitle': 'تحالفات استراتيجية.',
    'international.certs.title': 'الشهادات والمؤهلات',
    'international.certs.subtitle': 'معتمدون. معترف بهم. موثوقون.',
    'international.stat.0': 'قارات',
    'international.stat.1': 'دولة مخدومة',
    'international.stat.2': 'مشروع دولي',
    'international.stat.3': 'شريك عالمي',
  },
}

interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
  dir: 'ltr' | 'rtl'
}

const LanguageContext = createContext<LangCtx>({
  lang: 'fr',
  setLang: () => {},
  t: (key) => key,
  dir: 'ltr',
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr')

  useEffect(() => {
    const stored = localStorage.getItem('gpe-lang') as Lang
    if (stored && ['fr', 'en', 'ar'].includes(stored)) setLangState(stored)
  }, [])

  useEffect(() => {
    const dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.dir = dir
    document.documentElement.lang = lang
  }, [lang])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('gpe-lang', l)
  }

  const t = (key: string) => t18n[lang]?.[key] ?? t18n.fr[key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir: lang === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
