'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Lang = 'fr' | 'en' | 'ar'

const t18n: Record<Lang, Record<string, string>> = {
  /* ─────────────────────────── FRANÇAIS ─────────────────────────── */
  fr: {
    // ── Navbar
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.realisations': 'Réalisations',
    'nav.international': "À l'international",
    'nav.contact': 'Contact',
    'nav.cta': 'Demander un devis',

    // ── Hero
    'hero.eyebrow': 'Alger',
    'hero.title.part1': "L'énergie qui",
    'hero.title.highlight': 'donne vie',
    'hero.title.part2': 'à vos propriétés.',
    'hero.subtitle': "Installations électriques, énergies renouvelables, CVC, VRD et bureau d'études. Des solutions intégrées pour les professionnels et les collectivités exigeants.",
    'hero.cta.contact': 'Contactez-nous',
    'hero.cta.services': 'Nos Services',
    'hero.stat.years': "Années d'expérience",
    'hero.stat.projects': 'Projets réalisés',
    'hero.stat.expertise': 'Expertises métier',
    'hero.stat.satisfaction': 'Clients satisfaits',

    // ── Services section
    'services.label': 'Nos expertises',
    'services.title': 'Des solutions complètes,\nde la conception à la réalisation.',
    'services.subtitle': "Huit métiers complémentaires pour répondre à l'ensemble de vos besoins en énergie et en bâtiment.",
    'services.learnMore': 'En savoir plus',

    // ── References section
    'references.label': 'Nos réalisations',
    'references.title': 'Ils nous font confiance.',
    'references.subtitle': "Plus de 500 projets réalisés pour des maîtres d'ouvrage publics et privés partout en France.",
    'references.viewAll': 'Voir tous les projets',
    'references.featured': 'Projets de référence',
    'references.cta': 'Explorer tous nos projets',

    // ── About section
    'about.label': 'Notre histoire',
    'about.title.main': 'Bâtir un avenir électrique,',
    'about.title.highlight': 'ensemble.',
    'about.p1': "Fondée en 2008 à Lyon, GPE Énergies & Services est née de la conviction que l'excellence technique et l'innovation énergétique doivent aller de pair. En quinze ans, nous avons accompagné des centaines de maîtres d'ouvrage dans leur transition vers des bâtiments plus performants, plus économes et plus durables.",
    'about.p2': "Notre approche multidisciplinaire — électricité, renouvelables, CVC, VRD et ingénierie — nous permet de traiter un projet dans sa globalité, en garantissant cohérence technique, respect des délais et maîtrise des coûts.",
    'about.value0.title': 'Excellence technique',
    'about.value0.desc': "Chaque installation est réalisée dans les règles de l'art, certifiée et contrôlée par nos équipes qualifiées.",
    'about.value1.title': 'Engagement durable',
    'about.value1.desc': "Nous plaçons la transition énergétique au cœur de nos projets, pour un impact positif sur l'environnement.",
    'about.value2.title': 'Partenariat long terme',
    'about.value2.desc': 'Nos clients sont nos partenaires. Nous construisons des relations de confiance sur la durée, du projet à la maintenance.',
    'about.stat.founded': 'Création',
    'about.stat.team': 'Collaborateurs',
    'about.stat.region': "Région d'intervention",
    'about.stat.regionVal': 'Sud',

    // ── Footer
    'footer.tagline': "Expert en installations électriques, énergies renouvelables et solutions CVC depuis 2008.",
    'footer.nav.title': 'Navigation',
    'footer.services.title': 'Nos services',
    'footer.contact.title': 'Contact',
    'footer.response': 'Réponse sous 24h ouvrées',
    'footer.copyright': 'Tous droits réservés.',
    'footer.links.legal': 'Mentions légales',
    'footer.links.privacy': 'Politique de confidentialité',
    'footer.links.cgv': 'CGV',
    'footer.nav.home': 'Accueil',
    'footer.nav.services': 'Services',
    'footer.nav.references': 'Réalisations',
    'footer.nav.about': 'À propos',
    'footer.nav.contact': 'Contact',

    // ── Service page
    'service.back': 'Tous nos services',
    'service.expertise.label': 'Notre expertise',
    'service.expertise.title': 'Ce que nous réalisons pour vous',
    'service.benefits.title': 'Nos prestations incluses',
    'service.process.title': 'Notre processus',
    'service.process.0.title': 'Analyse & Étude',
    'service.process.0.desc': 'Audit technique de votre site et analyse de vos besoins spécifiques.',
    'service.process.1.title': 'Conception & Devis',
    'service.process.1.desc': 'Proposition technique détaillée avec chiffrage transparent et délais engagés.',
    'service.process.2.title': 'Réalisation',
    'service.process.2.desc': 'Exécution par nos équipes certifiées, avec suivi de chantier rigoureux.',
    'service.process.3.title': 'Réception & SAV',
    'service.process.3.desc': 'Mise en service, formation et contrat de maintenance adapté.',
    'service.cta.prefix': 'Un projet',
    'service.cta.suffix': '?',
    'service.cta.subtitle': 'Obtenez une étude personnalisée et un devis gratuit sous 24h.',
    'service.cta.quote': 'Demander un devis',
    'service.cta.call': 'Nous appeler',
    'service.certs.title': 'Certifications',
    'service.related.title': 'Services complémentaires',
    'service.projects.title': 'Projets réalisés',
    'service.projects.viewAll': 'Voir tous',

    // ── Service titles (for dynamic pages)

    "service.energies-renouvelables.title": "Énergies renouvelables",
    "service.courants-forts-faibles.title": "Courants forts & faibles",
    "service.mobilite-electrique.title": "Mobilité électrique",
    "service.gtb-knx.title": "GTB / KNX",
    "service.chauffage-climatisation.title": "Chauffage & climatisation",
    "service.renovation-energetique.title": "Rénovation énergétique",
    "service.bureau-etudes.title": "Bureau d'études",


    // ── Contact page
    'contact.label': 'Contact',
    'contact.title': 'Parlons de votre projet.',
    'contact.sub': "Notre équipe répond sous 24h ouvrées. Que ce soit pour un devis, une étude de faisabilité ou une question technique, nous sommes à votre écoute.",
    'contact.info.phone': 'Téléphone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Adresse',
    'contact.hours.title': 'Horaires',
    'contact.hours.weekdays': 'Lundi – Vendredi',
    'contact.hours.weekdaysTime': '8h00 – 18h00',
    'contact.hours.weekend': 'Samedi – Dimanche',
    'contact.hours.closed': 'Fermé',
    'contact.form.name': 'Nom complet *',
    'contact.form.namePlaceholder': 'Jean Dupont',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'jean@exemple.fr',
    'contact.form.phone': 'Téléphone',
    'contact.form.phonePlaceholder': '+33 6 XX XX XX XX',
    'contact.form.company': 'Société',
    'contact.form.companyPlaceholder': 'Votre entreprise',
    'contact.form.service': 'Service concerné',
    'contact.form.serviceDefault': 'Sélectionnez un service',
    'contact.form.message': 'Votre message *',
    'contact.form.messagePlaceholder': 'Décrivez votre projet ou votre demande...',
    'contact.form.messageError': 'Veuillez détailler votre message (min. 20 caractères)',
    'contact.form.submit': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.error': "Une erreur s'est produite. Veuillez réessayer ou nous contacter par téléphone.",
    'contact.form.privacy': "En envoyant ce formulaire, vous acceptez notre politique de confidentialité.",
    'contact.success.title': 'Message envoyé !',
    'contact.success.message': 'Merci pour votre message. Notre équipe vous répondra dans les 24h ouvrées.',
    'contact.success.button': 'Nouveau message',

    // ── Réalisations
    'realisations.label': 'Nos réalisations',
    'realisations.title': "Des projets qui parlent d'eux-mêmes.",
    'realisations.sub': "Plus de 500 projets réalisés pour des maîtres d'ouvrage publics et privés partout en France.",
    'realisations.all': 'Tous les projets',
    'realisations.empty': 'Aucun projet dans cette catégorie.',
    'realisations.cta.title': 'Un projet similaire ?',
    'realisations.cta.subtitle': "Discutons de votre projet. Notre équipe d'experts vous répond sous 24h ouvrées.",
    'realisations.cta.button': 'Nous contacter',

    // ── International
    'international.hero.label': 'Présence mondiale',
    'international.hero.title': 'Au-delà des frontières.',
    'international.hero.sub': "GPE Énergies & Services accompagne des projets d'envergure en France et à l'international, en apportant son expertise technique sur chaque continent.",
    'international.locations.title': 'Nos implantations',
    'international.map.title': 'Une présence sur 3 continents.',
    'international.partners.title': 'Partenaires internationaux',
    'international.partners.subtitle': 'Des alliances stratégiques.',
    'international.certs.title': 'Certifications & qualifications',
    'international.certs.subtitle': 'Certifiés. Reconnus. Fiables.',
    'international.stat.0': 'Continents',
    'international.stat.1': 'Pays couverts',
    'international.stat.2': 'Projets internationaux',
    'international.stat.3': 'Partenaires mondiaux',
  },

  /* ─────────────────────────── ENGLISH ─────────────────────────── */
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.realisations': 'Projects',
    'nav.international': 'International',
    'nav.contact': 'Contact',
    'nav.cta': 'Request a quote',

    'hero.eyebrow': 'Algiers',
    'hero.title.part1': 'The energy that',
    'hero.title.highlight': 'brings life',
    'hero.title.part2': 'to your properties.',
    'hero.subtitle': "Electrical installations, renewable energy, HVAC, civil works, and engineering consultancy. Integrated solutions for demanding professionals and local authorities.",
    'hero.cta.contact': 'Contact us',
    'hero.cta.services': 'Our Services',
    'hero.stat.years': 'Years of experience',
    'hero.stat.projects': 'Completed projects',
    'hero.stat.expertise': 'Areas of expertise',
    'hero.stat.satisfaction': 'Client satisfaction',

    'services.label': 'Our expertise',
    'services.title': 'Complete solutions,\nfrom design to delivery.',
    'services.subtitle': 'Eight complementary trades to meet all your energy and building needs.',
    'services.learnMore': 'Learn more',

    'references.label': 'Our projects',
    'references.title': 'They trust us.',
    'references.subtitle': 'Over 500 projects completed for public and private clients across France.',
    'references.viewAll': 'View all projects',
    'references.featured': 'Featured projects',
    'references.cta': 'Explore all our projects',

    'about.label': 'Our story',
    'about.title.main': 'Building an electrical future,',
    'about.title.highlight': 'together.',
    'about.p1': 'Founded in 2008 in Lyon, GPE Énergies & Services was built on the conviction that technical excellence and energy innovation must go hand in hand. Over fifteen years, we have supported hundreds of project owners in their transition toward more efficient, economical, and sustainable buildings.',
    'about.p2': 'Our multidisciplinary approach — electricity, renewables, HVAC, civil works, and engineering — allows us to handle a project in its entirety, ensuring technical coherence, deadline compliance, and cost control.',
    'about.value0.title': 'Technical Excellence',
    'about.value0.desc': 'Every installation is carried out to the highest standards, certified and inspected by our qualified teams.',
    'about.value1.title': 'Sustainable Commitment',
    'about.value1.desc': 'We place the energy transition at the heart of our projects, for a positive environmental impact.',
    'about.value2.title': 'Long-term Partnership',
    'about.value2.desc': 'Our clients are our partners. We build lasting trust-based relationships, from project inception through maintenance.',
    'about.stat.founded': 'Founded',
    'about.stat.team': 'Team members',
    'about.stat.region': 'Service region',
    'about.stat.regionVal': 'South',

    'footer.tagline': 'Expert in electrical installations, renewable energy, and HVAC solutions since 2008.',
    'footer.nav.title': 'Navigation',
    'footer.services.title': 'Our services',
    'footer.contact.title': 'Contact',
    'footer.response': 'Response within 24 business hours',
    'footer.copyright': 'All rights reserved.',
    'footer.links.legal': 'Legal notices',
    'footer.links.privacy': 'Privacy policy',
    'footer.links.cgv': 'Terms of service',
    'footer.nav.home': 'Home',
    'footer.nav.services': 'Services',
    'footer.nav.references': 'Projects',
    'footer.nav.about': 'About us',
    'footer.nav.contact': 'Contact',

    'service.back': 'All our services',
    'service.expertise.label': 'Our expertise',
    'service.expertise.title': 'What we deliver for you',
    'service.benefits.title': 'Included services',
    'service.process.title': 'Our process',
    'service.process.0.title': 'Analysis & Study',
    'service.process.0.desc': 'Technical audit of your site and analysis of your specific needs.',
    'service.process.1.title': 'Design & Quote',
    'service.process.1.desc': 'Detailed technical proposal with transparent pricing and committed timelines.',
    'service.process.2.title': 'Implementation',
    'service.process.2.desc': 'Execution by our certified teams with rigorous site supervision.',
    'service.process.3.title': 'Handover & Support',
    'service.process.3.desc': 'Commissioning, training, and a tailored maintenance contract.',
    'service.cta.prefix': 'A',
    'service.cta.suffix': 'project?',
    'service.cta.subtitle': 'Get a personalised study and a free quote within 24 hours.',
    'service.cta.quote': 'Request a quote',
    'service.cta.call': 'Call us',
    'service.certs.title': 'Certifications',
    'service.related.title': 'Complementary services',
    'service.projects.title': 'Completed projects',
    'service.projects.viewAll': 'View all',

    
    "service.energies-renouvelables.title": "Renewable Energy",
    "service.courants-forts-faibles.title": "High & Low Voltage Systems",
    "service.mobilite-electrique.title": "Electric Mobility",
    "service.gtb-knx.title": "Building Automation (GTB / KNX)",
    "service.chauffage-climatisation.title": "Heating & Air Conditioning",
    "service.renovation-energetique.title": "Energy Renovation",
    "service.bureau-etudes.title": "Engineering Office",


    'contact.label': 'Contact',
    'contact.title': "Let's talk about your project.",
    'contact.sub': 'Our team responds within 24 business hours. Whether for a quote, a feasibility study, or a technical question, we are here for you.',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.address': 'Address',
    'contact.hours.title': 'Opening hours',
    'contact.hours.weekdays': 'Monday – Friday',
    'contact.hours.weekdaysTime': '8:00 AM – 6:00 PM',
    'contact.hours.weekend': 'Saturday – Sunday',
    'contact.hours.closed': 'Closed',
    'contact.form.name': 'Full name *',
    'contact.form.namePlaceholder': 'John Smith',
    'contact.form.email': 'Email *',
    'contact.form.emailPlaceholder': 'john@example.com',
    'contact.form.phone': 'Phone',
    'contact.form.phonePlaceholder': '+33 6 XX XX XX XX',
    'contact.form.company': 'Company',
    'contact.form.companyPlaceholder': 'Your company',
    'contact.form.service': 'Service needed',
    'contact.form.serviceDefault': 'Select a service',
    'contact.form.message': 'Your message *',
    'contact.form.messagePlaceholder': 'Describe your project or request...',
    'contact.form.messageError': 'Please provide more details (min. 20 characters)',
    'contact.form.submit': 'Send message',
    'contact.form.sending': 'Sending...',
    'contact.form.error': 'Something went wrong. Please try again or contact us by phone.',
    'contact.form.privacy': 'By submitting this form, you agree to our privacy policy.',
    'contact.success.title': 'Message sent!',
    'contact.success.message': 'Thank you for your message. Our team will get back to you within 24 business hours.',
    'contact.success.button': 'New message',

    'realisations.label': 'Our projects',
    'realisations.title': 'Projects that speak for themselves.',
    'realisations.sub': 'Over 500 projects completed for public and private clients across France.',
    'realisations.all': 'All projects',
    'realisations.empty': 'No projects in this category.',
    'realisations.cta.title': 'A similar project?',
    'realisations.cta.subtitle': 'Let\'s discuss your project. Our expert team responds within 24 business hours.',
    'realisations.cta.button': 'Contact us',

    'international.hero.label': 'Global presence',
    'international.hero.title': 'Beyond borders.',
    'international.hero.sub': 'GPE Énergies & Services supports large-scale projects in France and internationally, bringing technical expertise to every continent.',
    'international.locations.title': 'Our locations',
    'international.map.title': 'Present across 3 continents.',
    'international.partners.title': 'International partners',
    'international.partners.subtitle': 'Strategic alliances.',
    'international.certs.title': 'Certifications & qualifications',
    'international.certs.subtitle': 'Certified. Recognised. Reliable.',
    'international.stat.0': 'Continents',
    'international.stat.1': 'Countries served',
    'international.stat.2': 'International projects',
    'international.stat.3': 'Global partners',
  },

  /* ─────────────────────────── ARABIC ─────────────────────────── */
  ar: {
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.realisations': 'مشاريعنا',
    'nav.international': 'دولي',
    'nav.contact': 'اتصل بنا',
    'nav.cta': 'طلب عرض أسعار',

    'hero.eyebrow': 'الجزائر العاصمة',
    'hero.title.part1': 'الطاقة التي',
    'hero.title.highlight': 'تُحيي',
    'hero.title.part2': 'ممتلكاتكم.',
    'hero.subtitle': 'تركيبات كهربائية، طاقات متجددة، تكييف وتهوية، بنية تحتية، ومكتب الدراسات. حلول متكاملة للمحترفين والهيئات الحكومية المتطلبة.',
    'hero.cta.contact': 'تواصل معنا',
    'hero.cta.services': 'خدماتنا',
    'hero.stat.years': 'سنوات خبرة',
    'hero.stat.projects': 'مشروع منجز',
    'hero.stat.expertise': 'تخصص تقني',
    'hero.stat.satisfaction': 'رضا العملاء',

    'services.label': 'خبراتنا',
    'services.title': 'حلول شاملة\nمن التصميم إلى التنفيذ.',
    'services.subtitle': 'ثمانية تخصصات متكاملة لتلبية كافة احتياجاتكم في مجال الطاقة والبناء.',
    'services.learnMore': 'اكتشف المزيد',

    'references.label': 'إنجازاتنا',
    'references.title': 'يثقون بنا.',
    'references.subtitle': 'أكثر من ٥٠٠ مشروع منجز لعملاء من القطاع العام والخاص في جميع أنحاء فرنسا.',
    'references.viewAll': 'عرض جميع المشاريع',
    'references.featured': 'مشاريع مرجعية',
    'references.cta': 'استكشف جميع مشاريعنا',

    'about.label': 'قصتنا',
    'about.title.main': 'نبني مستقبلاً كهربائياً،',
    'about.title.highlight': 'معاً.',
    'about.p1': 'تأسست GPE Énergies & Services عام ٢٠٠٨ في ليون، إيماناً بأن التميّز التقني والابتكار في مجال الطاقة يجب أن يسيرا جنباً إلى جنب. وعلى مدى خمسة عشر عاماً، رافقنا المئات من أصحاب المشاريع في مسيرتهم نحو مبانٍ أكثر كفاءةً وترشيداً واستدامةً.',
    'about.p2': 'يُتيح لنا نهجنا متعدد التخصصات — من الكهرباء والطاقات المتجددة، إلى التكييف والبنية التحتية والهندسة — إدارة المشروع بأكمله بتناسق تقني، والتزام بالمواعيد، والتحكم الكامل في التكاليف.',
    'about.value0.title': 'التميز التقني',
    'about.value0.desc': 'كل تركيب يُنجز وفق أعلى المعايير المهنية، معتمداً ومفحوصاً من قِبل فرقنا المؤهلة.',
    'about.value1.title': 'الالتزام بالاستدامة',
    'about.value1.desc': 'نضع التحول الطاقوي في صميم مشاريعنا، سعياً لأثر إيجابي حقيقي على البيئة.',
    'about.value2.title': 'شراكة طويلة الأمد',
    'about.value2.desc': 'عملاؤنا هم شركاؤنا الحقيقيون. نبني علاقات ثقة راسخة، من الإنجاز إلى الصيانة.',
    'about.stat.founded': 'تأسيس',
    'about.stat.team': 'موظف',
    'about.stat.region': 'منطقة التدخل',
    'about.stat.regionVal': 'الجنوب',

    'footer.tagline': 'خبراء في التركيبات الكهربائية والطاقات المتجددة وأنظمة التكييف منذ ٢٠٠٨.',
    'footer.nav.title': 'التنقل',
    'footer.services.title': 'خدماتنا',
    'footer.contact.title': 'تواصل معنا',
    'footer.response': 'رد خلال ٢٤ ساعة عمل',
    'footer.copyright': 'جميع الحقوق محفوظة.',
    'footer.links.legal': 'الإشعارات القانونية',
    'footer.links.privacy': 'سياسة الخصوصية',
    'footer.links.cgv': 'الشروط العامة',
    'footer.nav.home': 'الرئيسية',
    'footer.nav.services': 'الخدمات',
    'footer.nav.references': 'مشاريعنا',
    'footer.nav.about': 'من نحن',
    'footer.nav.contact': 'اتصل بنا',

    'service.back': 'جميع خدماتنا',
    'service.expertise.label': 'خبرتنا',
    'service.expertise.title': 'ما نُنجزه من أجلكم',
    'service.benefits.title': 'الخدمات المشمولة',
    'service.process.title': 'منهجيتنا',
    'service.process.0.title': 'التحليل والدراسة',
    'service.process.0.desc': 'تدقيق تقني لموقعكم وتحليل شامل لاحتياجاتكم الخاصة.',
    'service.process.1.title': 'التصميم والعرض',
    'service.process.1.desc': 'مقترح تقني مفصّل بتسعير شفاف والتزام بالمواعيد.',
    'service.process.2.title': 'التنفيذ',
    'service.process.2.desc': 'تنفيذ احترافي بواسطة فرقنا المعتمدة وإشراف ميداني دقيق.',
    'service.process.3.title': 'الاستلام والدعم',
    'service.process.3.desc': 'التشغيل والتدريب وعقد الصيانة الأنسب لاحتياجاتكم.',
    'service.cta.prefix': 'مشروع',
    'service.cta.suffix': '؟',
    'service.cta.subtitle': 'احصل على دراسة مخصصة وعرض أسعار مجاني خلال ٢٤ ساعة.',
    'service.cta.quote': 'طلب عرض أسعار',
    'service.cta.call': 'اتصل بنا',
    'service.certs.title': 'الشهادات والاعتمادات',
    'service.related.title': 'خدمات مكملة',
    'service.projects.title': 'المشاريع المنجزة',
    'service.projects.viewAll': 'عرض الكل',

    "service.energies-renouvelables.title": "الطاقات المتجددة",
    "service.courants-forts-faibles.title": "التيارات القوية والضعيفة",
    "service.mobilite-electrique.title": "التنقل الكهربائي",
    "service.gtb-knx.title": "أنظمة التحكم الذكي (GTB / KNX)",
    "service.chauffage-climatisation.title": "التدفئة والتكييف",
    "service.renovation-energetique.title": "تجديد الطاقة",
    'service.bureau-etudes.title': "مكتب الدراسات",

    'contact.label': 'تواصل معنا',
    'contact.title': 'لنتحدث عن مشروعكم.',
    'contact.sub': 'يرد فريقنا خلال ٢٤ ساعة عمل. سواء لعرض أسعار أو دراسة جدوى أو سؤال تقني، نحن هنا لمساعدتكم.',
    'contact.info.phone': 'هاتف',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.address': 'العنوان',
    'contact.hours.title': 'أوقات العمل',
    'contact.hours.weekdays': 'الإثنين – الجمعة',
    'contact.hours.weekdaysTime': '٨:٠٠ – ١٨:٠٠',
    'contact.hours.weekend': 'السبت – الأحد',
    'contact.hours.closed': 'مغلق',
    'contact.form.name': 'الاسم الكامل *',
    'contact.form.namePlaceholder': 'محمد الأمين',
    'contact.form.email': 'البريد الإلكتروني *',
    'contact.form.emailPlaceholder': 'example@domain.com',
    'contact.form.phone': 'الهاتف',
    'contact.form.phonePlaceholder': '+213 6 XX XX XX XX',
    'contact.form.company': 'الشركة',
    'contact.form.companyPlaceholder': 'اسم شركتكم',
    'contact.form.service': 'الخدمة المطلوبة',
    'contact.form.serviceDefault': 'اختر خدمة',
    'contact.form.message': 'رسالتكم *',
    'contact.form.messagePlaceholder': 'صفوا مشروعكم أو طلبكم...',
    'contact.form.messageError': 'يُرجى تفصيل رسالتكم (٢٠ حرفاً على الأقل)',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.sending': 'جارٍ الإرسال...',
    'contact.form.error': 'حدث خطأ. يرجى المحاولة مجدداً أو الاتصال بنا هاتفياً.',
    'contact.form.privacy': 'بإرسال هذا النموذج، تقبلون سياسة الخصوصية الخاصة بنا.',
    'contact.success.title': 'تم إرسال رسالتكم!',
    'contact.success.message': 'شكراً لتواصلكم. سيرد فريقنا خلال ٢٤ ساعة عمل.',
    'contact.success.button': 'رسالة جديدة',

    'realisations.label': 'إنجازاتنا',
    'realisations.title': 'مشاريع تتحدث عن نفسها.',
    'realisations.sub': 'أكثر من ٥٠٠ مشروع منجز لعملاء من القطاع العام والخاص في جميع أنحاء فرنسا.',
    'realisations.all': 'جميع المشاريع',
    'realisations.empty': 'لا توجد مشاريع في هذه الفئة.',
    'realisations.cta.title': 'مشروع مماثل؟',
    'realisations.cta.subtitle': 'لنتحدث عن مشروعكم. فريق خبرائنا يرد خلال ٢٤ ساعة عمل.',
    'realisations.cta.button': 'تواصل معنا',

    'international.hero.label': 'حضور عالمي',
    'international.hero.title': 'ما وراء الحدود.',
    'international.hero.sub': 'تدعم GPE Énergies & Services مشاريع واسعة النطاق في فرنسا وعلى الصعيد الدولي، مع تقديم خبرات تقنية راسخة على كل قارة.',
    'international.locations.title': 'مواقعنا',
    'international.map.title': 'حضور على ٣ قارات.',
    'international.partners.title': 'شركاؤنا الدوليون',
    'international.partners.subtitle': 'تحالفات استراتيجية.',
    'international.certs.title': 'الشهادات والمؤهلات',
    'international.certs.subtitle': 'معتمدون. معترف بهم. موثوقون.',
    'international.stat.0': 'قارات',
    'international.stat.1': 'دولة مخدومة',
    'international.stat.2': 'مشروع دولي',
    'international.stat.3': 'شريك عالمي',
  },
}

interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
  dir: 'ltr' | 'rtl'
}

const LanguageContext = createContext<LangCtx>({
  lang: 'fr',
  setLang: () => {},
  t: (key) => key,
  dir: 'ltr',
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr')

  useEffect(() => {
    const stored = localStorage.getItem('gpe-lang') as Lang
    if (stored && ['fr', 'en', 'ar'].includes(stored)) setLangState(stored)
  }, [])

  useEffect(() => {
    const dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.dir = dir
    document.documentElement.lang = lang
  }, [lang])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('gpe-lang', l)
  }

  const t = (key: string) => t18n[lang]?.[key] ?? t18n.fr[key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir: lang === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
